### ISSUE TITLE
About AVA datasets

### ISSUE THREAD

**Issue by chanwo0kim** [brjathu/LART#11]
Hello, 

First of all, thank you for the interesting research you presented!

Of the benchmarks you used, I'm interested in the AVA dataset.

I downloaded AVA raw video, so how can I create an image frame that matches the annotation you published?

I can not match the human with GT bounding boxes.

What should I do? I will wait for your reply.

Best regards,
Chanwoo

**Comment by brjathu** [comment]
Thank you.

We followed this process to get raw frames : https://github.com/facebookresearch/SlowFast/blob/main/slowfast/datasets/DATASET.md

Please let me know if you face any issues regarding this.

**Comment by chanwo0kim** [comment]
Thank you for your response!

I have one more question.

I am currently creating a 3D mesh from the ground-truth you provided. 
However, I'm unsure about how to handle depth when multiple people appear in a single image.

Currently, I am modifying the 'cam' part at the end of the pose_shape (maybe corresponding to "Location" in the PHALP paper) as follows: For x, y, I added x and y. And for depth, I used np.exp and reciprocal.

When I use this approach, the resulting 3D output doesn't seem to align well. 
Could you provide guidance?

Thank you!

Best regards,
Chanwoo
![스크린샷, 2023-08-22 23-38-47](https://github.com/brjathu/L
![스크린샷, 2023-08-22 23-39-28](https://github.com/brjathu/LART/assets/68315955/6a356515-2fc8-4569-9ac0-83b40f06846f)
ART/assets/68315955/c929c82f-6f95-40
![스크린샷, 2023-08-22 23-39-24](https://github.com/brjathu/LART/assets/68315955/bf626dcf-08c0-4253-a709-e46bdbbafd70)
![스크린샷, 2023-08-22 23-39-18](https://github.com/brjathu/LART/assets/68315955/094bff0e-d6ec-470d-b894-ad8b64d5c89f)
15-8bb8-465f790b2d29)

**Comment by brjathu** [comment]
Hi @chanwo0kim,

In PHALP, the `cam` parameter is converted to nearness (log(1/depth)) for measuring similarity between tracks. We only use nearness for solving the Hungarian matrix, but in the `pkl` files the cam parameter is directly stored. So you don't need to do this conversion, and directly adding the `cam` to the SMPL meshes would give reasonable depth ordering.

**Comment by chanwo0kim** [comment]
Okay! Thank you for your kindness!
