### ISSUE TITLE
Training code needs the "Demo on videos" stuffs

### ISSUE THREAD

**Issue by daviduarte** [brjathu/LART#15]
Hello, congratulations on your work!

I cloned the repository and followed the instructions in the "Training and Evaluation" section. However, I encountered a "ModuleNotFoundError: No module named 'lart.ActivityNet'" error, indicating that the 'lart.ActivityNet' file was missing. I resolved this error by following the additional instructions provided in the "Demo on videos" section, which allowed me to download the remaining files. I suggest adding a note to the README advising users to follow the "Demo on videos" section before proceeding with the "Training and Evaluation" section.

**Comment by brjathu** [comment]
Thanks for the update, I have updated the README.
