### ISSUE TITLE
Script to generate tracks and features

### ISSUE THREAD

**Issue by gurkirt** [brjathu/LART#3]
@brjathu Great work. Thank you for sharing
May request to make script avaible in public to generate data in the format found in https://github.com/brjathu/LART/blob/main/scripts/download_data.sh. I want to apply this to multisports.

Thanks
Gurkirt

**Comment by brjathu** [comment]
Hi, We have updated [PHALP](https://github.com/brjathu/PHALP) in this commit [475b1d1](https://github.com/brjathu/PHALP/commit/475b1d191d45fb5703cb3f8f1c02212a0c05dc6d) with support to save `.pkl` files as required by LART dataset. 

Please reinstall phalp package, and then run the demo.py.
```bash
python scripts/demo.py video.source="assets/jump.mp4"
```

This will create `.pkl` files for each track under `outputs/results_temporal_fast`. Once all these tracks are generated, please specify the paths with corresponding dataset names here: https://github.com/brjathu/LART/blob/b9bfc91ef15971f94384d7ae5dcde3a951fe4fc0/lart/datamodules/components/phalp_action_datatset.py#L50

For example:
```python
"posetrack_train"  : ["",    "outputs/results_temporal_fast", 1], 
```

and then you can train on your own dataset by running the following command.
```bash
python lart/train.py -m \
--config-name lart.yaml \
trainer=ddp_unused \
task_name=LART \
trainer.devices=1 \
trainer.num_nodes=1 \
configs.extra_feat.apperance.dim=1152 \
```

However, the current demo code only supports MViT backbone, so the feature dimensions must be set to 1152. Also, the pseudo labels will be still on the AVA labels space. If you have your own ground truth labels you can store them inside the generated `.pkl` files by updating the key `action_label_gt`.

Hope this helps, please feel free to ask if you have more questions. 

We are also planning to release the preprocessed data for AVA-Kinetics and Multisports soon. 

Thanks.

**Comment by brjathu** [comment]
Closing this issue, since it is inactive for a while, please feel free to reopen it if you have further questions.

**Comment by daviduarte** [comment]
Hi, I'm trying to generate the .pkl files for all tracks in the demo video:

`python scripts/demo.py video.source="assets/jump.mp4"
`
But the results are not being written in the folder **outputs/results_temporal_fast**.

I'm using the commit from Wed Aug 9, after the commit you mentioned above ([475b1d1](https://github.com/brjathu/PHALP/commit/475b1d191d45fb5703cb3f8f1c02212a0c05dc6d)). 

I already set the `save_fast_tracks = True` on phalp/configs/base.py, as well as `save_fast_tracks = true` on outputs/.hydra/config.yaml, but the tracks are not beeing saved. The folder **results_temporal_fast** is not even being created. 

Do you have any suggestion? 
Thanks!

**Comment by vtn98** [comment]
Hi @brjathu
I ran demo.py, but .pkl file is not generated for each track in output/results_temporal_fast
Can you help me?
