### ISSUE TITLE
Sequences are slightly lagged?

### ISSUE THREAD

**Issue by saraswat** [brjathu/LART#5]
The output video has on the left the original video and on the right the reconstructed video with SMPL skins for humans.  Now, when the system is run on a video with very fast actions by humans (e.g. hands are moving extremely rapidly) it appears that there is a perceptible lag between the LHS and the RHS. 

Do you know why? Is it known to be constant (in which case it does not matter, one can just adjust the two) or does it vary on some parameters (e.g. time, complexity of preceding actions)...?

**Comment by saraswat** [comment]
(BTW, this should show up in PHALP. Do you want me to verify in PHALP and open a ticket on that project?)

**Comment by brjathu** [comment]
Hi @saraswat, Thanks for finding this bug, could you please provide a video or a link, so that I can try to debug on my end?

**Comment by saraswat** [comment]
Try this: https://www.youtube.com/watch?v=uWF322D94vc, round 5.

**Comment by brjathu** [comment]
I used this video with this command: `python scripts/demo.py video.source=2.mp4`

https://github.com/brjathu/LART/assets/7527097/26f3f9cf-9d49-4d8a-b351-a22402a437bb


and this was the output from our end, I don't see any lags, but if you have any other videos, please share them with us to debug. 


https://github.com/brjathu/LART/assets/7527097/f2b962ba-e5d4-49cb-b3c2-03bd94ad4a94

**Comment by brjathu** [comment]
Closing this issue, since it is inactive for a while, please feel free to reopen it if you have further questions.
