### ISSUE TITLE
Demo not generating sequences

### ISSUE THREAD

**Issue by ak3ra** [brjathu/LART#6]
The demo colab notebook seems broken. Everything installs alright but on running the demo:

`!python scripts/demo.py video.source="assets/jump.mp4" +half=True
`
No sequences are generated, hence:

`FileNotFoundError: [Errno 2] No such file or directory: 'outputs/results_temporal_videos/'`

**Comment by brjathu** [comment]
Could you please try again, the server was down for a while, which might have caused the code to break when downloading the weights, I just tried now, and it is working fine.

**Comment by brjathu** [comment]
Closing this issue, since it is inactive for a while, please feel free to reopen it if you have further questions.

**Comment by TJor-L** [comment]
I got the same problem in Colab Notebook
